"""Generate JSON Schema and TypeScript contracts from Pydantic models."""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from planguard.artifacts.models import ANY_ARTIFACT_ADAPTER, ARTIFACT_MODELS


def _safe_name(name: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if cleaned and cleaned[0].isdigit():
        cleaned = f"_{cleaned}"
    return cleaned or "Anonymous"


def _literal(value: Any) -> str:
    if value is None:
        return "null"
    if value is True:
        return "true"
    if value is False:
        return "false"
    if isinstance(value, str):
        return json.dumps(value)
    return str(value)


def _schema_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return _safe_name(schema["$ref"].split("/")[-1])
    if "const" in schema:
        return _literal(schema["const"])
    if "enum" in schema:
        return " | ".join(_literal(item) for item in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(_schema_type(item) for item in schema["anyOf"])
    if "oneOf" in schema:
        return " | ".join(_schema_type(item) for item in schema["oneOf"])

    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return " | ".join(_schema_type({**schema, "type": item}) for item in schema_type)
    if schema_type == "string":
        return "string"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"
    if schema_type == "array":
        return f"Array<{_schema_type(schema.get('items', {}))}>"
    if schema_type == "object" or "properties" in schema:
        properties = schema.get("properties", {})
        required = set(schema.get("required", []))
        if properties:
            lines = ["{"]
            for key, prop_schema in properties.items():
                optional = "" if key in required else "?"
                lines.append(
                    f"  {json.dumps(key)}{optional}: {_schema_type(prop_schema)};"
                )
            additional = schema.get("additionalProperties")
            if isinstance(additional, dict):
                lines.append(f"  [key: string]: {_schema_type(additional)};")
            lines.append("}")
            return "\n".join(lines)
        additional = schema.get("additionalProperties", True)
        if isinstance(additional, dict):
            return f"Record<string, {_schema_type(additional)}>"
        return "Record<string, unknown>"
    return "unknown"




def _materialize_persisted_schema(node: Any, *, property_name: str | None = None) -> None:
    """Mutate a Pydantic schema into PlanGuard's canonical persisted-document profile.

    Canonical encoding emits explicit defaults and nulls, so every declared model property is
    required in stored documents. `content_hash` is additionally required to be a non-null
    qualified SHA-256 value. Internal Python models may still be constructed unsealed.
    """

    if isinstance(node, list):
        for item in node:
            _materialize_persisted_schema(item)
        return
    if not isinstance(node, dict):
        return

    properties = node.get("properties")
    if isinstance(properties, dict):
        node["required"] = sorted(properties)
        for name, child in properties.items():
            _materialize_persisted_schema(child, property_name=name)

    for key, child in list(node.items()):
        if key != "properties":
            _materialize_persisted_schema(child, property_name=property_name)

    if property_name == "content_hash":
        node.clear()
        node.update({
            "type": "string",
            "pattern": r"^sha256:[0-9a-f]{64}$",
            "title": "Content Hash",
        })


def typescript_from_schema(schema: dict[str, Any]) -> str:
    lines = [
        "/* This file is generated by scripts/generate_contracts.py. */",
        "/* Do not edit it by hand. */",
        "",
        "export type JsonPrimitive = string | number | boolean | null;",
        "export type JsonValue = JsonPrimitive | JsonValue[] | { [key: string]: JsonValue };",
        "",
    ]
    defs = schema.get("$defs", {})
    for name in sorted(defs):
        ts_name = _safe_name(name)
        rendered = _schema_type(defs[name])
        if rendered.startswith("{"):
            lines.append(f"export interface {ts_name} {rendered}")
        else:
            lines.append(f"export type {ts_name} = {rendered};")
        lines.append("")
    root_schema = {key: value for key, value in schema.items() if key != "$defs"}
    lines.append(f"export type AnyArtifact = {_schema_type(root_schema)};")
    lines.append("")
    lines.extend([
        "export type MaterializedArtifact = AnyArtifact & {",
        "  artifact_id: string;",
        "  artifact_kind: string;",
        "  schema_version: string;",
        "  created_at: string;",
        "  provenance: Provenance;",
        "  extensions: Record<string, Record<string, unknown>>;",
        "  content_hash: string;",
        "};",
        "",
        "export interface ArtifactSummary {",
        "  artifact_id: string;",
        "  artifact_kind: string;",
        "  schema_version: string;",
        "  created_at: string;",
        "  content_hash: string;",
        "}",
    ])
    lines.append("")
    return "\n".join(lines)


def generate_contracts(schema_dir: Path, typescript_path: Path) -> None:
    schema_dir.mkdir(parents=True, exist_ok=True)
    typescript_path.parent.mkdir(parents=True, exist_ok=True)

    any_schema = ANY_ARTIFACT_ADAPTER.json_schema(
        mode="validation",
        ref_template="#/$defs/{model}",
    )
    _materialize_persisted_schema(any_schema)
    any_schema["$schema"] = "https://json-schema.org/draft/2020-12/schema"
    any_schema["$id"] = "https://planguard.dev/schemas/planguard.any-artifact.v1.json"
    any_schema["title"] = "PlanGuard Any Artifact v1"
    (schema_dir / "planguard.any-artifact.v1.schema.json").write_text(
        json.dumps(any_schema, sort_keys=True, indent=2) + "\n",
        encoding="utf-8",
    )

    catalog: dict[str, str] = {}
    for model in ARTIFACT_MODELS:
        schema = model.model_json_schema(mode="validation", ref_template="#/$defs/{model}")
        _materialize_persisted_schema(schema)
        schema["$schema"] = "https://json-schema.org/draft/2020-12/schema"
        kind = str(model.model_fields["artifact_kind"].default)
        version = str(model.model_fields["schema_version"].default)
        filename = f"{version}.schema.json"
        schema["$id"] = f"https://planguard.dev/schemas/{filename}"
        (schema_dir / filename).write_text(
            json.dumps(schema, sort_keys=True, indent=2) + "\n",
            encoding="utf-8",
        )
        catalog[f"{kind}/{version}"] = filename

    (schema_dir / "catalog.json").write_text(
        json.dumps(catalog, sort_keys=True, indent=2) + "\n",
        encoding="utf-8",
    )
    typescript_path.write_text(typescript_from_schema(any_schema), encoding="utf-8")
