import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { evaluateRunPolicy, listRuns, type ArtifactDocumentLike, type RunListItem } from "../lib/api";
import { JsonTree } from "../components/JsonTree";

export function PolicyStudioPage() {
  const [runs, setRuns] = useState<RunListItem[]>([]);
  const [runId, setRunId] = useState("");
  const [maxQueries, setMaxQueries] = useState(20);
  const [maxFamily, setMaxFamily] = useState(5);
  const [forbidNPlusOne, setForbidNPlusOne] = useState(true);
  const [evaluation, setEvaluation] = useState<ArtifactDocumentLike | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [running, setRunning] = useState(false);

  useEffect(() => {
    listRuns().then((response) => {
      setRuns(response.items);
      if (response.items.length) setRunId(response.items[0].artifact_id);
    }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : String(reason)));
  }, []);

  const payload = useMemo(() => {
    const rules: Array<Record<string, unknown>> = [
      { rule_key: "max-query-count", subject_kind: "run", metric: "query_count", selector: null, operator: "less_or_equal", threshold: maxQueries, disposition: "fail", message: null },
      { rule_key: "max-family-executions", subject_kind: "family", metric: "payload.aggregates.execution_count", selector: null, operator: "less_or_equal", threshold: maxFamily, disposition: "fail", message: null },
    ];
    if (forbidNPlusOne) rules.push({
      rule_key: "forbid-likely-n-plus-one",
      subject_kind: "finding",
      metric: null,
      selector: { operator: "equals", field: "payload.detector_key", value: "likely-n-plus-one.v1", children: [] },
      operator: "no_matches",
      threshold: null,
      disposition: "fail",
      message: null,
    });
    return { policy_key: "workbench-draft.v1", title: "Workbench draft policy", rules, description: "Generated by the Milestone B Policy Studio.", tags: ["workbench"] };
  }, [maxQueries, maxFamily, forbidNPlusOne]);

  const handleEvaluate = async () => {
    setRunning(true); setError(null);
    try { setEvaluation(await evaluateRunPolicy(runId, payload)); }
    catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); }
    finally { setRunning(false); }
  };

  return <section>
    <header className="page-header"><div><p className="eyebrow">Regression prevention</p><h1>Policy Studio</h1><p>Build an absolute query budget, preview its canonical payload, and evaluate it against an immutable completed run.</p></div></header>
    {error && <div className="error-banner" role="alert">{error}</div>}
    <div className="policy-grid">
      <article className="panel control-stack">
        <label>Run<select value={runId} onChange={(event) => setRunId(event.target.value)}>{runs.map((run) => <option key={run.artifact_id} value={run.artifact_id}>{run.name}</option>)}</select></label>
        <label>Maximum query count<input type="number" min="0" value={maxQueries} onChange={(event) => setMaxQueries(Number(event.target.value))} /></label>
        <label>Maximum executions per family<input type="number" min="0" value={maxFamily} onChange={(event) => setMaxFamily(Number(event.target.value))} /></label>
        <label className="checkbox-row"><input type="checkbox" checked={forbidNPlusOne} onChange={(event) => setForbidNPlusOne(event.target.checked)} /> Forbid likely N+1 findings</label>
        <button type="button" className="primary-button" disabled={!runId || running} onClick={handleEvaluate}>{running ? "Evaluating…" : "Evaluate and persist"}</button>
      </article>
      <article className="panel"><h2>Canonical policy payload</h2><JsonTree value={payload} /></article>
    </div>
    {evaluation && <article className="panel evaluation-panel"><div className="section-heading"><div><h2>Evaluation result</h2><p>Status: <strong>{String(evaluation.payload.status)}</strong></p></div><Link to={`/artifacts/${evaluation.artifact_id}`}>Open artifact</Link></div><JsonTree value={evaluation.payload.rule_evaluations} /></article>}
  </section>;
}
