"""PlanGuard developer MVP."""

from .analysis import AnalysisBundle, AnalysisEngine, build_workload, load_analysis_bundle
from .artifacts.codec import ArtifactCodec, default_codec
from .artifacts.models import (
    AnyArtifact,
    ArtifactDocument,
    ArtifactReference,
    BudgetPolicyArtifact,
    CapabilityGapArtifact,
    CapturePolicyArtifact,
    EnvironmentProfileArtifact,
    FindingArtifact,
    ObservedQueryFamilyArtifact,
    QueryExecutionArtifact,
    QueryTemplateArtifact,
    RunManifestArtifact,
    ScenarioBindingArtifact,
    ScenarioInstanceArtifact,
    ScenarioRunArtifact,
    ScenarioTemplateArtifact,
    DatasetManifestArtifact,
    MutationDefinitionArtifact,
    PlanObservationArtifact,
    PlanCollectionReceiptArtifact,
    ComparisonReportArtifact,
    UniverseProfileArtifact,
    RepresentativeSetArtifact,
    CoverageReportArtifact,
    NoveltySignatureArtifact,
    CounterexampleCandidateArtifact,
    MinimizationRunArtifact,
    CorpusPromotionArtifact,
    WorkloadEpisodeArtifact,
    WorkloadGraphArtifact,
    WorkloadMotifArtifact,
)
from .capture import AnalysisSession, profile
from .policy import QueryPolicy, evaluate_policy
from .scenario import OperationResult, ScenarioRegistry, ScenarioRunner, instantiate, scale, contrast
from .postgres import PlanCollectionPolicy, analyze_plan, collect_plan, import_plan, normalize_postgres_plan, observation_from_raw_plan
from .comparison import compare_runs
from .universe import (
    build_django_postgres_universe, evaluate_coverage, generate_representative_set,
    evaluate_novelty, create_counterexample, minimize_counterexample,
    promote_counterexample,
)
from .store.filesystem import FilesystemArtifactStore
from .store.index import ArtifactIndex

__all__ = [
    "AnalysisBundle",
    "AnalysisEngine",
    "AnalysisSession",
    "AnyArtifact",
    "ArtifactCodec",
    "ArtifactDocument",
    "ArtifactReference",
    "ArtifactIndex",
    "BudgetPolicyArtifact",
    "CapabilityGapArtifact",
    "CapturePolicyArtifact",
    "EnvironmentProfileArtifact",
    "FilesystemArtifactStore",
    "FindingArtifact",
    "ObservedQueryFamilyArtifact",
    "QueryExecutionArtifact",
    "QueryPolicy",
    "QueryTemplateArtifact",
    "RunManifestArtifact",
    "ScenarioBindingArtifact",
    "ScenarioInstanceArtifact",
    "ScenarioRunArtifact",
    "ScenarioTemplateArtifact",
    "DatasetManifestArtifact",
    "MutationDefinitionArtifact",
    "PlanObservationArtifact",
    "PlanCollectionReceiptArtifact",
    "ComparisonReportArtifact",
    "UniverseProfileArtifact",
    "RepresentativeSetArtifact",
    "CoverageReportArtifact",
    "NoveltySignatureArtifact",
    "CounterexampleCandidateArtifact",
    "MinimizationRunArtifact",
    "CorpusPromotionArtifact",
    "PlanCollectionPolicy",
    "ScenarioRegistry",
    "ScenarioRunner",
    "OperationResult",
    "WorkloadEpisodeArtifact",
    "WorkloadGraphArtifact",
    "WorkloadMotifArtifact",
    "build_workload",
    "default_codec",
    "evaluate_policy",
    "load_analysis_bundle",
    "profile",
    "instantiate",
    "scale",
    "contrast",
    "analyze_plan",
    "collect_plan",
    "import_plan",
    "normalize_postgres_plan",
    "observation_from_raw_plan",
    "compare_runs",
    "build_django_postgres_universe",
    "evaluate_coverage",
    "generate_representative_set",
    "evaluate_novelty",
    "create_counterexample",
    "minimize_counterexample",
    "promote_counterexample",
]

__version__ = "0.6.0"
