from django.urls import path

from . import views

urlpatterns = [
    path("health", views.health, name="health"),
    path("capabilities", views.capabilities, name="capabilities"),
    path("registry/stats", views.registry_stats, name="registry-stats"),
    path("registry/rebuild", views.rebuild_registry, name="registry-rebuild"),
    path("artifacts", views.artifacts, name="artifacts"),
    path("artifacts/<str:artifact_id>", views.artifact_detail, name="artifact-detail"),
    path("artifacts/<str:artifact_id>/integrity", views.artifact_integrity, name="artifact-integrity"),
    path("artifacts/<str:artifact_id>/related", views.artifact_related, name="artifact-related"),
    path("import", views.import_artifact, name="import-artifact"),
    path("runs", views.runs, name="runs"),
    path("runs/<str:run_id>", views.run_detail, name="run-detail"),
    path("runs/<str:run_id>/families", views.run_families, name="run-families"),
    path("runs/<str:run_id>/findings", views.run_findings, name="run-findings"),
    path("runs/<str:run_id>/graph", views.run_graph, name="run-graph"),
    path("runs/<str:run_id>/episodes", views.run_episodes, name="run-episodes"),
    path("runs/<str:run_id>/export", views.export_run, name="run-export"),
    path("runs/<str:run_id>/policy-evaluations", views.evaluate_run_policy, name="run-policy-evaluation"),
    path("runs/<str:run_id>/plans", views.run_plans, name="run-plans"),
    path("runs/<str:run_id>/plans/import", views.import_run_plan, name="run-plan-import"),
    path("runs/<str:run_id>/plans/collect", views.collect_run_plan, name="run-plan-collect"),
    path("plans/<str:plan_id>", views.plan_detail, name="plan-detail"),
    path("comparisons", views.comparisons, name="comparisons"),
    path("comparisons/create", views.create_comparison, name="comparison-create"),
    path("comparisons/<str:comparison_id>", views.comparison_detail, name="comparison-detail"),
    path("motifs", views.motifs, name="motifs"),
    path("scenarios/catalog", views.scenario_catalog, name="scenario-catalog"),
    path("scenarios/instances", views.instantiate_scenario, name="scenario-instantiate"),
    path("scenarios/runs", views.scenario_runs, name="scenario-runs"),
    path("scenarios/run", views.execute_scenario, name="scenario-execute"),
    path("scenarios/runs/<str:scenario_run_id>", views.scenario_run_detail, name="scenario-run-detail"),
]
